name: Continuous Integration

on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: "3.13"

jobs:
  install-dependencies:
    name: Setup Dependencies
    runs-on: ubuntu-latest
    outputs:
      venv-path: ${{ steps.setup-poetry.outputs.venv-path }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Cache Poetry virtualenv
        uses: actions/cache@v3
        id: cache-venv
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install Dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-root

  lint:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Run Pylint
        run: |
          source .venv/bin/activate
          pylint loomi

  type-check:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Run Pyright
        run: |
          source .venv/bin/activate
          pyright loomi

  format:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Run Black
        run: |
          source .venv/bin/activate
          black --check loomi

  test:
    needs: install-dependencies
    runs-on: ubuntu-latest
    services:
      neo4j:
        image: neo4j:latest
        env:
          NEO4J_AUTH: neo4j/password
        ports:
          - 7687:7687
        options: >-
          --health-cmd "cypher-shell -u neo4j -p password 'RETURN 1;'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      memgraph:
        image: memgraph/memgraph
        env:
          MEMGRAPH: "--storage-properties-on-edges=true --log-level=TRACE"
          MEMGRAPH_USER: memgraph
          MEMGRAPH_PASSWORD: password
        ports:
          - 7688:7687
        options: >-
          --health-cmd "bash -c 'mgconsole -u memgraph -p password -e \"RETURN 0;\"'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Run Integration Tests
        env:
          NEO4J_URI: "bolt://localhost:7687"
          NEO4J_USER: neo4j
          NEO4J_PWD: password
          MEMGRAPH_URI: "bolt://localhost:7688"
          MEMGRAPH_USER: memgraph
          MEMGRAPH_PWD: password
        run: |
          source .venv/bin/activate
          pytest --cov=src tests/
